---
title: "Cell Type and State Simulation Data"
author: "Michel Tarnow"
date: today
format: 
    html:
      toc: true
      self-contained: true
      highlight-style: github
      code-line-numbers: true
editor_options: 
    chunk_output_type: inline
---

## Import Packages

```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(zellkonverter)
})
```

## Load Data

```{r}
sce_raw <- readRDS("../../data/sim/00-raw/t100,s80,b0.rds")
sce <- readRDS("../../data/sim/01-pro/t100,s80,b0.rds")
cd <- readRDS("../../data/sim/01-pro/t100,s80,b0-cd.rds")
rd <- readRDS("../../data/sim/01-pro/t100,s80,b0-rd.rds")
```

# Summary and Exploration

```{r}
# dimensions
cat("Genes x Cells: \n", as.character(dim(sce)), "\n \n")

# gene and cell names
cat("Gene Names: \n", head(rownames(sce)), "... \n \n")
cat("Cell Names: \n", head(colnames(sce)), "... \n \n")

# assays
cat("Assays: \n", assayNames(sce), "\n \n")

# metadata
cat("Gene metadata: \n", colnames(rd), "\n \n")
cat("Cell metadata: \n", colnames(cd), "\n \n")
```

```{r}
ggplot(data = cd, mapping = aes(x = PC1, y = PC2, shape = cluster_id, colour = group_id)) +
  geom_point() +
  labs(title = "Cell Type and State",
       x = "PC1",
       y = "PC2",
       shape = "Cluster/Type",
       colour = "Condition/State") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
ggplot(data = cd, mapping = aes(x = PC1, y = PC2, colour = sample_id)) +
  geom_point() +
  labs(title = "Samples",
       x = "PC1",
       y = "PC2") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))
```

## Export Objects for Use in Python

```{r}
# sce object
sce_file <- "../../data/sim/01-pro/t100,s80,b0.h5ad"
writeH5AD(sce, sce_file)

# metadata dfs
write.csv(cd, "../../data/sim/01-pro/t100,s80,b0-cd.csv", row.names = TRUE)
write.csv(rd, "../../data/sim/01-pro/t100,s80,b0-rd.csv", row.names = TRUE)
```













